INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (1, 'Brett', 'Calestano', 'Spain');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (2, 'Chase', 'Hull', 'Christmas Island');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (3, 'Evan', 'Springfield', 'Marshall Islands');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (4, 'Charles', 'Maidenhead', 'Russian Federation');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (5, 'Guy', 'Akhtubinsk', 'Sint Maarten');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (6, 'Hunter', 'Nieuwkapelle', 'Mayotte');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (7, 'Brody', 'Thanjavur', 'Luxembourg');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (8, 'Drew', 'Achalpur', 'Saint Vincent and The Grenadines');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (9, 'Leroy', 'Naumburg', 'Pakistan');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (10, 'Davis', 'Iowa City', 'Iran');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (11, 'Blake', 'Drachten', 'Côte D''Ivoire (Ivory Coast)');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (12, 'Preston', 'Aschaffenburg', 'Greece');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (13, 'Keegan', 'Sainte-Marie-Chevigny', 'Libya');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (14, 'Igor', 'Zhukovsky', 'Venezuela');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (15, 'Slade', 'Bogotá', 'Ukraine');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (16, 'Reese', 'Butte', 'Romania');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (17, 'Jamal', 'Herselt', 'Cook Islands');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (18, 'Abdul', 'Saint-GŽry', 'Qatar');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (19, 'Ferris', 'Newmarket', 'Sao Tome and Principe');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (20, 'Ishmael', 'Carpignano Salentino', 'Macedonia');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (21, 'Thaddeus', 'El Retorno', 'Faroe Islands');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (22, 'Zachary', 'Bekegem', 'Korea, North');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (23, 'Neville', 'Barranca', 'Martinique');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (24, 'Jerome', 'Ligosullo', 'Gambia');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (25, 'Emery', 'McCallum', 'Burkina Faso');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (26, 'Oren', 'Talence', 'Panama');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (27, 'Hiram', 'Bunbury', 'French Guiana');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (28, 'Quentin', 'Benalla', 'United Kingdom (Great Britain)');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (29, 'Reuben', 'Baidyabati', 'San Marino');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (30, 'Flynn', 'Vitry-sur-Seine', 'Greenland');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (31, 'Garrett', 'Torchiarolo', 'Eritrea');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (32, 'Fuller', 'Silifke', 'Cocos (Keeling) Islands');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (33, 'John', 'Warwick', 'Oman');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (34, 'Erich', 'Pemberton', 'Guadeloupe');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (35, 'Ryder', 'Ferrere', 'Viet Nam');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (36, 'Yuli', 'Auburn', 'Comoros');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (37, 'George', 'Acquedolci', 'Belarus');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (38, 'Brendan', 'Puerto Guzmán', 'Iceland');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (39, 'Chase', 'Leverkusen', 'Guinea');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (40, 'Emery', 'Beaufays', 'Haiti');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (41, 'Troy', 'Chillán Viejo', 'Luxembourg');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (42, 'Tyrone', 'Ruisbroek', 'Mongolia');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (43, 'Elton', 'Jeonju', 'Turks and Caicos Islands');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (44, 'Gage', 'Fort Good Hope', 'Equatorial Guinea');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (45, 'Kasimir', 'Lichtaart', 'French Southern Territories');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (46, 'Timothy', 'Uberlândia', 'Azerbaijan');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (47, 'Lane', 'Nijmegen', 'Cayman Islands');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (48, 'Matthew', 'Falmouth', 'Mongolia');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (49, 'Addison', 'Hannut', 'Monaco');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (50, 'Hamish', 'Aurangabad', 'Gabon');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (51, 'Forrest', 'Timon', 'Turkey');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (52, 'Dieter', 'Terzorio', 'Curaçao');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (53, 'Jin', 'Meer', 'Guernsey');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (54, 'Ryder', 'Amqui', 'Timor-Leste');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (55, 'Jin', 'Saint-Servais', 'Saint Martin');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (56, 'Jason', 'Cambrai', 'Philippines');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (57, 'Steven', 'Bekegem', 'Seychelles');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (58, 'Hunter', 'Onega', 'South Georgia and The South Sandwich Islands');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (59, 'Thane', 'Leuze', 'Liechtenstein');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (60, 'Sebastian', 'Troitsk', 'Kiribati');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (61, 'Chandler', 'Vichy', 'Viet Nam');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (62, 'Bruno', 'Meeuwen-Gruitrode', 'Mauritius');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (63, 'Ezekiel', 'Lanklaar', 'Solomon Islands');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (64, 'Cooper', 'Schönebeck', 'Niger');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (65, 'Bruce', 'Sète', 'Ukraine');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (66, 'Jakeem', 'Driekapellen', 'Malaysia');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (67, 'Giacomo', 'Quimbaya', 'Norfolk Island');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (68, 'Kelly', 'Wayaux', 'Macao');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (69, 'Chase', 'Saint-Lô', 'Sao Tome and Principe');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (70, 'Stewart', 'Sherani', 'United States Minor Outlying Islands');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (71, 'Keefe', 'Grande Cache', 'Nauru');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (72, 'Rogan', 'Buti', 'Moldova');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (73, 'Jeremy', 'Neunkirchen', 'Uruguay');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (74, 'Jasper', 'Esslingen', 'Fiji');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (75, 'Jonah', 'Athens', 'French Guiana');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (76, 'Keane', 'Grande Cache', 'Afghanistan');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (77, 'Vincent', 'Vitrolles', 'Burundi');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (78, 'Tanek', 'Roosdaal', 'Western Sahara');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (79, 'Tarik', 'Chichester', 'Faroe Islands');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (80, 'Hamish', 'Sawahlunto', 'Canada');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (81, 'Reuben', 'Codognè', 'Lebanon');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (82, 'Hamilton', 'Río Claro', 'Saint Lucia');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (83, 'Kenneth', 'Swan Hills', 'Slovenia');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (84, 'Ashton', 'Dolcedo', 'Faroe Islands');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (85, 'Robert', 'Berg', 'Vanuatu');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (86, 'Burton', 'Cambridge', 'Benin');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (87, 'Elmo', 'Fort McPherson', 'Falkland Islands');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (88, 'Xenos', 'Plato', 'Tonga');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (89, 'Hedley', 'Düsseldorf', 'Denmark');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (90, 'Barry', 'Gibsons', 'Kuwait');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (91, 'Lawrence', 'Windermere', 'Argentina');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (92, 'Joseph', 'Konstanz', 'Rwanda');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (93, 'Jarrod', 'Ortacesus', 'Wallis and Futuna');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (94, 'Jordan', 'Fort Smith', 'Christmas Island');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (95, 'Michael', 'Tulsa', 'Norfolk Island');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (96, 'Rashad', 'Ife', 'Croatia');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (97, 'Gareth', 'San Miguel', 'Lesotho');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (98, 'Keaton', 'Zirl', 'Uruguay');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (99, 'Raymond', 'Frederick', 'Netherlands');
INSERT INTO public.mytables (id, nombre, ciudad, pais) VALUES (100, 'Patrick', 'Reutlingen', 'Indonesia');